openapi: 3.0.0
info:
  title: Go CRUD Person
  version: '0.0.1-alpha.0'
  description: |
    Documentação da API Rest do **Go CRUD Person** no padrão OpenAPI 3.0.

  contact:
    name: guilhermerodrigues680
    url: https://github.com/guilhermerodrigues680

servers:
  - url: 'http://localhost:8080/api/v1'
    description: Local

paths:

  /:
    get:
      tags:
        - default
      summary: Retorna a versao da api
      description: |
        ## Retorna a versao da api
      responses:
        '200':
          description: Um texto
          content:
            text/html;charset=UTF-8:
              example: |-
                "go-crud-person 0.0.1-alpha.0"

  /error:
    get:
      tags:
        - default
      summary: Retorna um erro no padrão da API
      description: |
        ## Retorna um erro no padrão da API
      responses:
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'


tags:
  - name: default
    description: Rotas da API Rest

components:

  schemas:
    error:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: number
          format: int32
        error:
          type: string
        message:
          type: string
        path:
          type: string
      example:
        timestamp: '2021-01-29T18:01:35.676+00:00'
        status: 400
        error: 'Bad Request'
        message: 'Mensagem detalhando o motivo'
        path: '/api/v1/error'
